//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShunFengExpressPostOrderInfo.ShunFengPushPack {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.expressservice.integration.sf.com/", ConfigurationName="ShunFengPushPack.IService")]
    public interface IService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponse sfexpressService(ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponse> sfexpressServiceAsync(ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressService", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceBody Body;
        
        public sfexpressService() {
        }
        
        public sfexpressService(ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public sfexpressServiceBody() {
        }
        
        public sfexpressServiceBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressServiceResponse", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponseBody Body;
        
        public sfexpressServiceResponse() {
        }
        
        public sfexpressServiceResponse(ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sfexpressServiceResponseBody() {
        }
        
        public sfexpressServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ShunFengExpressPostOrderInfo.ShunFengPushPack.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ShunFengExpressPostOrderInfo.ShunFengPushPack.IService>, ShunFengExpressPostOrderInfo.ShunFengPushPack.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponse ShunFengExpressPostOrderInfo.ShunFengPushPack.IService.sfexpressService(ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService request) {
            return base.Channel.sfexpressService(request);
        }
        
        public string sfexpressService(string arg0) {
            ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService inValue = new ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService();
            inValue.Body = new ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceBody();
            inValue.Body.arg0 = arg0;
            ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponse retVal = ((ShunFengExpressPostOrderInfo.ShunFengPushPack.IService)(this)).sfexpressService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponse> ShunFengExpressPostOrderInfo.ShunFengPushPack.IService.sfexpressServiceAsync(ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService request) {
            return base.Channel.sfexpressServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceResponse> sfexpressServiceAsync(string arg0) {
            ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService inValue = new ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressService();
            inValue.Body = new ShunFengExpressPostOrderInfo.ShunFengPushPack.sfexpressServiceBody();
            inValue.Body.arg0 = arg0;
            return ((ShunFengExpressPostOrderInfo.ShunFengPushPack.IService)(this)).sfexpressServiceAsync(inValue);
        }
    }
}
