//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class authority
    {
        public authority()
        {
            this.accountauthority = new HashSet<accountauthority>();
        }
    
        public int Id { get; set; }
        public int AuthorityType { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<accountauthority> accountauthority { get; set; }
    }
}
