//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienter
    {
        public int Id { get; set; }
        public string PhoneNo { get; set; }
        public string LoginName { get; set; }
        public string recommendPhone { get; set; }
        public string Password { get; set; }
        public string TrueName { get; set; }
        public string IDCard { get; set; }
        public string PicWithHandUrl { get; set; }
        public string PicUrl { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public string InviteCode { get; set; }
        public string City { get; set; }
        public string CityId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string HealthCardID { get; set; }
        public string InternalDepart { get; set; }
        public string ProvinceCode { get; set; }
        public string AreaCode { get; set; }
        public string CityCode { get; set; }
        public string Province { get; set; }
        public Nullable<int> BussinessID { get; set; }
    }
}
