//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class clienter
    {
        public int Id { get; set; }
        public string PhoneNo { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string TrueName { get; set; }
        public string IDCard { get; set; }
        public string PicWithHandUrl { get; set; }
        public string PicUrl { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public Nullable<decimal> AccountBalance { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public string InviteCode { get; set; }
        public string City { get; set; }
        public string CityId { get; set; }
    }
}
