//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public long Id { get; set; }
        public string GroupName { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<sbyte> IsValid { get; set; }
    }
}
