//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class myincome
    {
        public int Id { get; set; }
        public string PhoneNo { get; set; }
        public string MyIncome1 { get; set; }
        public Nullable<decimal> MyInComeAmount { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    }
}
