//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public string PickUpAddress { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public string ReceviceName { get; set; }
        public string RecevicePhoneNo { get; set; }
        public string ReceviceAddress { get; set; }
        public Nullable<System.DateTime> ActualDoneDate { get; set; }
        public Nullable<bool> IsPay { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> OrderCommission { get; set; }
        public Nullable<decimal> DistribSubsidy { get; set; }
        public Nullable<decimal> WebsiteSubsidy { get; set; }
        public string Remark { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public Nullable<int> clienterId { get; set; }
        public Nullable<int> businessId { get; set; }
        public string ReceviceCity { get; set; }
        public Nullable<double> ReceviceLongitude { get; set; }
        public Nullable<double> ReceviceLatitude { get; set; }
        public sbyte OrderFrom { get; set; }
        public Nullable<long> OriginalOrderId { get; set; }
        public string OriginalOrderNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual business business { get; set; }
    }
}
