//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderlog
    {
        public long Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public string OptionDescription { get; set; }
        public string OptionPerson { get; set; }
        public Nullable<System.DateTime> OptionTIme { get; set; }
        public Nullable<byte> IsValid { get; set; }
        public string Remark { get; set; }
    }
}
