//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderlog
    {
        public long Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public string OptionDescription { get; set; }
        public string OptionPerson { get; set; }
        public Nullable<System.DateTime> OptionTIme { get; set; }
        public Nullable<byte> IsValid { get; set; }
        public string Remark { get; set; }
    }
}
