//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pushmessage
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Alert { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PushDate { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
