//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class pushmessagestatus
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public Nullable<int> AndroidDeliveredCount { get; set; }
        public Nullable<int> PushMessageId { get; set; }
    }
}
