//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ChnName { get; set; }
        public string BriefName { get; set; }
        public string EnName { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int Fid { get; set; }
        public int Provinceid { get; set; }
        public int Cityid { get; set; }
        public int Depth { get; set; }
        public Nullable<int> Isbroad { get; set; }
        public string QPing { get; set; }
        public string JPing { get; set; }
        public string BriefQPing { get; set; }
        public string BriefJPing { get; set; }
        public Nullable<bool> IsGov { get; set; }
        public string Host { get; set; }
        public string BaiduLat { get; set; }
        public string BaiduLong { get; set; }
    }
}
