//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class region
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ChnName { get; set; }
        public string BriefName { get; set; }
        public string EnName { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int Fid { get; set; }
        public int Provinceid { get; set; }
        public int Cityid { get; set; }
        public int Depth { get; set; }
        public Nullable<int> Isbroad { get; set; }
        public string QPing { get; set; }
        public string JPing { get; set; }
        public string BriefQPing { get; set; }
        public string BriefJPing { get; set; }
        public Nullable<bool> IsGov { get; set; }
        public string Host { get; set; }
        public string BaiduLat { get; set; }
        public string BaiduLong { get; set; }
    }
}
