//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsidy
    {
        public int Id { get; set; }
        public Nullable<decimal> OrderCommission { get; set; }
        public Nullable<decimal> DistribSubsidy { get; set; }
        public Nullable<decimal> WebsiteSubsidy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<sbyte> Status { get; set; }
    }
}
