//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class supermanEntities : DbContext
    {
        public supermanEntities()
            : base("name=supermanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<accountauthority> accountauthority { get; set; }
        public virtual DbSet<areacity> areacity { get; set; }
        public virtual DbSet<areacounty> areacounty { get; set; }
        public virtual DbSet<areaprovice> areaprovice { get; set; }
        public virtual DbSet<authority> authority { get; set; }
        public virtual DbSet<business> business { get; set; }
        public virtual DbSet<channel> channel { get; set; }
        public virtual DbSet<clienter> clienter { get; set; }
        public virtual DbSet<commissiontype> commissiontype { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<myincome> myincome { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderlog> orderlog { get; set; }
        public virtual DbSet<pushmessage> pushmessage { get; set; }
        public virtual DbSet<pushmessagestatus> pushmessagestatus { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<subsidy> subsidy { get; set; }
    }
}
