//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperManDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class supermanEntities : DbContext
    {
        public supermanEntities()
            : base("name=supermanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<accountauthority> accountauthority { get; set; }
        public virtual DbSet<areacity> areacity { get; set; }
        public virtual DbSet<areacounty> areacounty { get; set; }
        public virtual DbSet<authority> authority { get; set; }
        public virtual DbSet<channel> channel { get; set; }
        public virtual DbSet<commissiontype> commissiontype { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<myincome> myincome { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderlog> orderlog { get; set; }
        public virtual DbSet<pushmessage> pushmessage { get; set; }
        public virtual DbSet<pushmessagestatus> pushmessagestatus { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<subsidy> subsidy { get; set; }
        public virtual DbSet<areaprovice> areaprovice { get; set; }
        public virtual DbSet<business> business { get; set; }
        public virtual DbSet<clienter> clienter { get; set; }
    }
}
