//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.SMSServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsSendType", Namespace="http://tempuri.org/")]
    public enum SmsSendType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        亿美软通 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        营销渠道 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        天润融通 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        百分通联 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        云信 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        梦网 = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSServiceReference.SmsSoap")]
    public interface SmsSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsResponse SendSms(ETS.SMSServiceReference.SendSmsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsResult", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsResultResponse SendSmsResult(ETS.SMSServiceReference.SendSmsResultRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLog", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsSaveLogResponse SendSmsSaveLog(ETS.SMSServiceReference.SendSmsSaveLogRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogNoSign", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsSaveLogNoSignResponse SendSmsSaveLogNoSign(ETS.SMSServiceReference.SendSmsSaveLogNoSignRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogNew", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsSaveLogNewResponse SendSmsSaveLogNew(ETS.SMSServiceReference.SendSmsSaveLogNewRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsSaveLogB2B", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsSaveLogB2BResponse SendSmsSaveLogB2B(ETS.SMSServiceReference.SendSmsSaveLogB2BRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSendedSmsResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendedSms", ReplyAction="*")]
        ETS.SMSServiceReference.GetSendedSmsResponse GetSendedSms(ETS.SMSServiceReference.GetSendedSmsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoiceSendSms", ReplyAction="*")]
        ETS.SMSServiceReference.VoiceSendSmsResponse VoiceSendSms(ETS.SMSServiceReference.VoiceSendSmsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBaseSaveLog", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsBaseSaveLogResponse SendSmsBaseSaveLog(ETS.SMSServiceReference.SendSmsBaseSaveLogRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSmsBase", ReplyAction="*")]
        ETS.SMSServiceReference.SendSmsBaseResponse SendSmsBase(ETS.SMSServiceReference.SendSmsBaseRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSmsSaveLog", ReplyAction="*")]
        ETS.SMSServiceReference.MsgSendSmsSaveLogResponse MsgSendSmsSaveLog(ETS.SMSServiceReference.MsgSendSmsSaveLogRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSendSms", ReplyAction="*")]
        ETS.SMSServiceReference.MsgSendSmsResponse MsgSendSms(ETS.SMSServiceReference.MsgSendSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(ETS.SMSServiceReference.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string Mobile, string Content) {
            this.Mobile = Mobile;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(ETS.SMSServiceReference.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResult", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsResultRequestBody Body;
        
        public SendSmsResultRequest() {
        }
        
        public SendSmsResultRequest(ETS.SMSServiceReference.SendSmsResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        public SendSmsResultRequestBody() {
        }
        
        public SendSmsResultRequestBody(string Mobile, string Content) {
            this.Mobile = Mobile;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsResultResponseBody Body;
        
        public SendSmsResultResponse() {
        }
        
        public SendSmsResultResponse(ETS.SMSServiceReference.SendSmsResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResultResult;
        
        public SendSmsResultResponseBody() {
        }
        
        public SendSmsResultResponseBody(string SendSmsResultResult) {
            this.SendSmsResultResult = SendSmsResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogRequestBody Body;
        
        public SendSmsSaveLogRequest() {
        }
        
        public SendSmsSaveLogRequest(ETS.SMSServiceReference.SendSmsSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isVoiceSms;
        
        public SendSmsSaveLogRequestBody() {
        }
        
        public SendSmsSaveLogRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.isVoiceSms = isVoiceSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogResponseBody Body;
        
        public SendSmsSaveLogResponse() {
        }
        
        public SendSmsSaveLogResponse(ETS.SMSServiceReference.SendSmsSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogResult;
        
        public SendSmsSaveLogResponseBody() {
        }
        
        public SendSmsSaveLogResponseBody(string SendSmsSaveLogResult) {
            this.SendSmsSaveLogResult = SendSmsSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNoSignRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNoSign", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogNoSignRequestBody Body;
        
        public SendSmsSaveLogNoSignRequest() {
        }
        
        public SendSmsSaveLogNoSignRequest(ETS.SMSServiceReference.SendSmsSaveLogNoSignRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNoSignRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isVoiceSms;
        
        public SendSmsSaveLogNoSignRequestBody() {
        }
        
        public SendSmsSaveLogNoSignRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.isVoiceSms = isVoiceSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNoSignResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNoSignResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogNoSignResponseBody Body;
        
        public SendSmsSaveLogNoSignResponse() {
        }
        
        public SendSmsSaveLogNoSignResponse(ETS.SMSServiceReference.SendSmsSaveLogNoSignResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNoSignResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogNoSignResult;
        
        public SendSmsSaveLogNoSignResponseBody() {
        }
        
        public SendSmsSaveLogNoSignResponseBody(string SendSmsSaveLogNoSignResult) {
            this.SendSmsSaveLogNoSignResult = SendSmsSaveLogNoSignResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNew", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogNewRequestBody Body;
        
        public SendSmsSaveLogNewRequest() {
        }
        
        public SendSmsSaveLogNewRequest(ETS.SMSServiceReference.SendSmsSaveLogNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isVoiceSms;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int groupId;
        
        public SendSmsSaveLogNewRequestBody() {
        }
        
        public SendSmsSaveLogNewRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms, int groupId) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.isVoiceSms = isVoiceSms;
            this.groupId = groupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogNewResponseBody Body;
        
        public SendSmsSaveLogNewResponse() {
        }
        
        public SendSmsSaveLogNewResponse(ETS.SMSServiceReference.SendSmsSaveLogNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogNewResult;
        
        public SendSmsSaveLogNewResponseBody() {
        }
        
        public SendSmsSaveLogNewResponseBody(string SendSmsSaveLogNewResult) {
            this.SendSmsSaveLogNewResult = SendSmsSaveLogNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogB2BRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogB2B", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogB2BRequestBody Body;
        
        public SendSmsSaveLogB2BRequest() {
        }
        
        public SendSmsSaveLogB2BRequest(ETS.SMSServiceReference.SendSmsSaveLogB2BRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogB2BRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int groupId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsPlatform;
        
        public SendSmsSaveLogB2BRequestBody() {
        }
        
        public SendSmsSaveLogB2BRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID, int groupId, string smsPlatform) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
            this.groupId = groupId;
            this.smsPlatform = smsPlatform;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsSaveLogB2BResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsSaveLogB2BResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsSaveLogB2BResponseBody Body;
        
        public SendSmsSaveLogB2BResponse() {
        }
        
        public SendSmsSaveLogB2BResponse(ETS.SMSServiceReference.SendSmsSaveLogB2BResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsSaveLogB2BResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsSaveLogB2BResult;
        
        public SendSmsSaveLogB2BResponseBody() {
        }
        
        public SendSmsSaveLogB2BResponseBody(string SendSmsSaveLogB2BResult) {
            this.SendSmsSaveLogB2BResult = SendSmsSaveLogB2BResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSendedSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSendedSms", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.GetSendedSmsRequestBody Body;
        
        public GetSendedSmsRequest() {
        }
        
        public GetSendedSmsRequest(ETS.SMSServiceReference.GetSendedSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSendedSmsRequestBody {
        
        public GetSendedSmsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSendedSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSendedSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.GetSendedSmsResponseBody Body;
        
        public GetSendedSmsResponse() {
        }
        
        public GetSendedSmsResponse(ETS.SMSServiceReference.GetSendedSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSendedSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSendedSmsResult;
        
        public GetSendedSmsResponseBody() {
        }
        
        public GetSendedSmsResponseBody(string GetSendedSmsResult) {
            this.GetSendedSmsResult = GetSendedSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoiceSendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VoiceSendSms", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.VoiceSendSmsRequestBody Body;
        
        public VoiceSendSmsRequest() {
        }
        
        public VoiceSendSmsRequest(ETS.SMSServiceReference.VoiceSendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VoiceSendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> supplierID;
        
        public VoiceSendSmsRequestBody() {
        }
        
        public VoiceSendSmsRequestBody(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VoiceSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VoiceSendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.VoiceSendSmsResponseBody Body;
        
        public VoiceSendSmsResponse() {
        }
        
        public VoiceSendSmsResponse(ETS.SMSServiceReference.VoiceSendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VoiceSendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VoiceSendSmsResult;
        
        public VoiceSendSmsResponseBody() {
        }
        
        public VoiceSendSmsResponseBody(string VoiceSendSmsResult) {
            this.VoiceSendSmsResult = VoiceSendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsBaseSaveLogRequestBody Body;
        
        public SendSmsBaseSaveLogRequest() {
        }
        
        public SendSmsBaseSaveLogRequest(ETS.SMSServiceReference.SendSmsBaseSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ETS.SMSServiceReference.SmsSendType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> supplierID;
        
        public SendSmsBaseSaveLogRequestBody() {
        }
        
        public SendSmsBaseSaveLogRequestBody(string mobile, string content, ETS.SMSServiceReference.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.type = type;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsBaseSaveLogResponseBody Body;
        
        public SendSmsBaseSaveLogResponse() {
        }
        
        public SendSmsBaseSaveLogResponse(ETS.SMSServiceReference.SendSmsBaseSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsBaseSaveLogResult;
        
        public SendSmsBaseSaveLogResponseBody() {
        }
        
        public SendSmsBaseSaveLogResponseBody(string SendSmsBaseSaveLogResult) {
            this.SendSmsBaseSaveLogResult = SendSmsBaseSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBase", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsBaseRequestBody Body;
        
        public SendSmsBaseRequest() {
        }
        
        public SendSmsBaseRequest(ETS.SMSServiceReference.SendSmsBaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ETS.SMSServiceReference.SmsSendType type;
        
        public SendSmsBaseRequestBody() {
        }
        
        public SendSmsBaseRequestBody(string Mobile, string Content, ETS.SMSServiceReference.SmsSendType type) {
            this.Mobile = Mobile;
            this.Content = Content;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsBaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsBaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.SendSmsBaseResponseBody Body;
        
        public SendSmsBaseResponse() {
        }
        
        public SendSmsBaseResponse(ETS.SMSServiceReference.SendSmsBaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsBaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsBaseResult;
        
        public SendSmsBaseResponseBody() {
        }
        
        public SendSmsBaseResponseBody(string SendSmsBaseResult) {
            this.SendSmsBaseResult = SendSmsBaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsSaveLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsSaveLog", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.MsgSendSmsSaveLogRequestBody Body;
        
        public MsgSendSmsSaveLogRequest() {
        }
        
        public MsgSendSmsSaveLogRequest(ETS.SMSServiceReference.MsgSendSmsSaveLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsSaveLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ETS.SMSServiceReference.SmsSendType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsSource;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> supplierID;
        
        public MsgSendSmsSaveLogRequestBody() {
        }
        
        public MsgSendSmsSaveLogRequestBody(string mobile, string content, ETS.SMSServiceReference.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            this.mobile = mobile;
            this.content = content;
            this.type = type;
            this.smsSource = smsSource;
            this.supplierID = supplierID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsSaveLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsSaveLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.MsgSendSmsSaveLogResponseBody Body;
        
        public MsgSendSmsSaveLogResponse() {
        }
        
        public MsgSendSmsSaveLogResponse(ETS.SMSServiceReference.MsgSendSmsSaveLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsSaveLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgSendSmsSaveLogResult;
        
        public MsgSendSmsSaveLogResponseBody() {
        }
        
        public MsgSendSmsSaveLogResponseBody(string MsgSendSmsSaveLogResult) {
            this.MsgSendSmsSaveLogResult = MsgSendSmsSaveLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSms", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.MsgSendSmsRequestBody Body;
        
        public MsgSendSmsRequest() {
        }
        
        public MsgSendSmsRequest(ETS.SMSServiceReference.MsgSendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public MsgSendSmsRequestBody() {
        }
        
        public MsgSendSmsRequestBody(string mobile, string content) {
            this.mobile = mobile;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsgSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsgSendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ETS.SMSServiceReference.MsgSendSmsResponseBody Body;
        
        public MsgSendSmsResponse() {
        }
        
        public MsgSendSmsResponse(ETS.SMSServiceReference.MsgSendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgSendSmsResult;
        
        public MsgSendSmsResponseBody() {
        }
        
        public MsgSendSmsResponseBody(string MsgSendSmsResult) {
            this.MsgSendSmsResult = MsgSendSmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSoapChannel : ETS.SMSServiceReference.SmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSoapClient : System.ServiceModel.ClientBase<ETS.SMSServiceReference.SmsSoap>, ETS.SMSServiceReference.SmsSoap {
        
        public SmsSoapClient() {
        }
        
        public SmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsResponse ETS.SMSServiceReference.SmsSoap.SendSms(ETS.SMSServiceReference.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string Mobile, string Content) {
            ETS.SMSServiceReference.SendSmsRequest inValue = new ETS.SMSServiceReference.SendSmsRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            ETS.SMSServiceReference.SendSmsResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsResultResponse ETS.SMSServiceReference.SmsSoap.SendSmsResult(ETS.SMSServiceReference.SendSmsResultRequest request) {
            return base.Channel.SendSmsResult(request);
        }
        
        public string SendSmsResult(string Mobile, string Content) {
            ETS.SMSServiceReference.SendSmsResultRequest inValue = new ETS.SMSServiceReference.SendSmsResultRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsResultRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            ETS.SMSServiceReference.SendSmsResultResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSmsResult(inValue);
            return retVal.Body.SendSmsResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsSaveLogResponse ETS.SMSServiceReference.SmsSoap.SendSmsSaveLog(ETS.SMSServiceReference.SendSmsSaveLogRequest request) {
            return base.Channel.SendSmsSaveLog(request);
        }
        
        public string SendSmsSaveLog(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            ETS.SMSServiceReference.SendSmsSaveLogRequest inValue = new ETS.SMSServiceReference.SendSmsSaveLogRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            ETS.SMSServiceReference.SendSmsSaveLogResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSmsSaveLog(inValue);
            return retVal.Body.SendSmsSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsSaveLogNoSignResponse ETS.SMSServiceReference.SmsSoap.SendSmsSaveLogNoSign(ETS.SMSServiceReference.SendSmsSaveLogNoSignRequest request) {
            return base.Channel.SendSmsSaveLogNoSign(request);
        }
        
        public string SendSmsSaveLogNoSign(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms) {
            ETS.SMSServiceReference.SendSmsSaveLogNoSignRequest inValue = new ETS.SMSServiceReference.SendSmsSaveLogNoSignRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsSaveLogNoSignRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            ETS.SMSServiceReference.SendSmsSaveLogNoSignResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSmsSaveLogNoSign(inValue);
            return retVal.Body.SendSmsSaveLogNoSignResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsSaveLogNewResponse ETS.SMSServiceReference.SmsSoap.SendSmsSaveLogNew(ETS.SMSServiceReference.SendSmsSaveLogNewRequest request) {
            return base.Channel.SendSmsSaveLogNew(request);
        }
        
        public string SendSmsSaveLogNew(string mobile, string content, string smsSource, System.Nullable<int> supplierID, bool isVoiceSms, int groupId) {
            ETS.SMSServiceReference.SendSmsSaveLogNewRequest inValue = new ETS.SMSServiceReference.SendSmsSaveLogNewRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsSaveLogNewRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.isVoiceSms = isVoiceSms;
            inValue.Body.groupId = groupId;
            ETS.SMSServiceReference.SendSmsSaveLogNewResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSmsSaveLogNew(inValue);
            return retVal.Body.SendSmsSaveLogNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsSaveLogB2BResponse ETS.SMSServiceReference.SmsSoap.SendSmsSaveLogB2B(ETS.SMSServiceReference.SendSmsSaveLogB2BRequest request) {
            return base.Channel.SendSmsSaveLogB2B(request);
        }
        
        public string SendSmsSaveLogB2B(string mobile, string content, string smsSource, System.Nullable<int> supplierID, int groupId, string smsPlatform) {
            ETS.SMSServiceReference.SendSmsSaveLogB2BRequest inValue = new ETS.SMSServiceReference.SendSmsSaveLogB2BRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsSaveLogB2BRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            inValue.Body.groupId = groupId;
            inValue.Body.smsPlatform = smsPlatform;
            ETS.SMSServiceReference.SendSmsSaveLogB2BResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSmsSaveLogB2B(inValue);
            return retVal.Body.SendSmsSaveLogB2BResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.GetSendedSmsResponse ETS.SMSServiceReference.SmsSoap.GetSendedSms(ETS.SMSServiceReference.GetSendedSmsRequest request) {
            return base.Channel.GetSendedSms(request);
        }
        
        public string GetSendedSms() {
            ETS.SMSServiceReference.GetSendedSmsRequest inValue = new ETS.SMSServiceReference.GetSendedSmsRequest();
            inValue.Body = new ETS.SMSServiceReference.GetSendedSmsRequestBody();
            ETS.SMSServiceReference.GetSendedSmsResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).GetSendedSms(inValue);
            return retVal.Body.GetSendedSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.VoiceSendSmsResponse ETS.SMSServiceReference.SmsSoap.VoiceSendSms(ETS.SMSServiceReference.VoiceSendSmsRequest request) {
            return base.Channel.VoiceSendSms(request);
        }
        
        public string VoiceSendSms(string mobile, string content, string smsSource, System.Nullable<int> supplierID) {
            ETS.SMSServiceReference.VoiceSendSmsRequest inValue = new ETS.SMSServiceReference.VoiceSendSmsRequest();
            inValue.Body = new ETS.SMSServiceReference.VoiceSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            ETS.SMSServiceReference.VoiceSendSmsResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).VoiceSendSms(inValue);
            return retVal.Body.VoiceSendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsBaseSaveLogResponse ETS.SMSServiceReference.SmsSoap.SendSmsBaseSaveLog(ETS.SMSServiceReference.SendSmsBaseSaveLogRequest request) {
            return base.Channel.SendSmsBaseSaveLog(request);
        }
        
        public string SendSmsBaseSaveLog(string mobile, string content, ETS.SMSServiceReference.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            ETS.SMSServiceReference.SendSmsBaseSaveLogRequest inValue = new ETS.SMSServiceReference.SendSmsBaseSaveLogRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsBaseSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            ETS.SMSServiceReference.SendSmsBaseSaveLogResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSmsBaseSaveLog(inValue);
            return retVal.Body.SendSmsBaseSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.SendSmsBaseResponse ETS.SMSServiceReference.SmsSoap.SendSmsBase(ETS.SMSServiceReference.SendSmsBaseRequest request) {
            return base.Channel.SendSmsBase(request);
        }
        
        public string SendSmsBase(string Mobile, string Content, ETS.SMSServiceReference.SmsSendType type) {
            ETS.SMSServiceReference.SendSmsBaseRequest inValue = new ETS.SMSServiceReference.SendSmsBaseRequest();
            inValue.Body = new ETS.SMSServiceReference.SendSmsBaseRequestBody();
            inValue.Body.Mobile = Mobile;
            inValue.Body.Content = Content;
            inValue.Body.type = type;
            ETS.SMSServiceReference.SendSmsBaseResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).SendSmsBase(inValue);
            return retVal.Body.SendSmsBaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.MsgSendSmsSaveLogResponse ETS.SMSServiceReference.SmsSoap.MsgSendSmsSaveLog(ETS.SMSServiceReference.MsgSendSmsSaveLogRequest request) {
            return base.Channel.MsgSendSmsSaveLog(request);
        }
        
        public string MsgSendSmsSaveLog(string mobile, string content, ETS.SMSServiceReference.SmsSendType type, string smsSource, System.Nullable<int> supplierID) {
            ETS.SMSServiceReference.MsgSendSmsSaveLogRequest inValue = new ETS.SMSServiceReference.MsgSendSmsSaveLogRequest();
            inValue.Body = new ETS.SMSServiceReference.MsgSendSmsSaveLogRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            inValue.Body.type = type;
            inValue.Body.smsSource = smsSource;
            inValue.Body.supplierID = supplierID;
            ETS.SMSServiceReference.MsgSendSmsSaveLogResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).MsgSendSmsSaveLog(inValue);
            return retVal.Body.MsgSendSmsSaveLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ETS.SMSServiceReference.MsgSendSmsResponse ETS.SMSServiceReference.SmsSoap.MsgSendSms(ETS.SMSServiceReference.MsgSendSmsRequest request) {
            return base.Channel.MsgSendSms(request);
        }
        
        public string MsgSendSms(string mobile, string content) {
            ETS.SMSServiceReference.MsgSendSmsRequest inValue = new ETS.SMSServiceReference.MsgSendSmsRequest();
            inValue.Body = new ETS.SMSServiceReference.MsgSendSmsRequestBody();
            inValue.Body.mobile = mobile;
            inValue.Body.content = content;
            ETS.SMSServiceReference.MsgSendSmsResponse retVal = ((ETS.SMSServiceReference.SmsSoap)(this)).MsgSendSms(inValue);
            return retVal.Body.MsgSendSmsResult;
        }
    }
}
